app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

//Pages
Route::get('/', [
    'as' => '/', 'uses' => 'PagesController@getIndex'
]);

//Authentication Routes
Route::auth();

Route::get('/home', 'HomeController@index');

//Clips
Route::resource('clip', 'ClipController');

//Tags
Route::resource('tag', 'TagController');

app/Clip.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Clip extends Model
{
   protected $fillable = [
   		'name',
   		'start_time',
   		'end_time'
   ];

   public $timestamps = false;
   protected $table = 'clips';

   public function tags()
   {
   		return $this->belongsToMany('App\Tag');
   }
}

app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function clips()
    {
    	return $this->belongsToMany('App\Clip');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/ClipController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Clip;

use App\Tag;

class ClipController extends Controller
{
   /**
     * Create a new controller instance.
     *
     * @return void
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    /**
     * Display a listing of video clips.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
    	$clips = Clip::all();

        return view('clips.index')->with('clips', $clips);
    }

    /**
     * Show the form for creating a new clip.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
    	return view('clips.create')->withTags($tags);
    }

     /**
     * Store a newly created clip in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate data
        $this->validate($request, array('name' => 'required|max:255'));
    	// $clip = new Clip;
    	// $clip->name = $request->name;
    	// $clip->start_time = $request->start_time;
    	// $clip->end_time = $request->end_time;

        //store in the database
    	$inputs = $request->all();
    	$clip = Clip::Create($inputs);

    	$clip->save();

        //sync relationship
        $clip->tags()->sync($request->tags, false);

    	return redirect()->route('clip.index');

    }

     /**
     * Display the specified clip.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
    	$clip = Clip::find($id);
    	return view('clips.show')->with('clip', $clip);
    }

    /**
     * Show the form for editing the specified clip.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        
    	$clip = Clip::find($id);

        $tags = Tag::all();
        $tags2 = array();
        foreach($tags as $tag)
        {
            $tags2[$tag->id] = $tag->name;
        }
    	return view('clips.edit', compact('clip', $clip))->withTags($tags2);
    }

    /**
     * Update the specified clip in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
    	$clip = Clip::find($id);
    	$clip->name = $request->name;
    	$clip->start_time = $request->start_time;
    	$clip->end_time = $request->end_time;

    	$clip->save();

         //sync relationship
        if(isset($request->tags)){
            $clip->tags()->sync($request->tags);   
        }else{
            $clip->tags()->sync(array());   
        }
        
    	return redirect()->route('clip.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    	$clip = Clip::find($id)->delete();
    	return redirect()->route('clip.index');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesResources;

class Controller extends BaseController
{
    use AuthorizesRequests, AuthorizesResources, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PagesController.php
<?php

namespace App\Http\Controllers;

// use App\User;
use App\Http\Controllers\Controller;

class PagesController extends Controller
{
    public function getIndex(){
        return view('welcome');
    }

}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

use App\Tag;

use Session;

class TagController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */

    public function __construct()
    {
        $this->middleware('auth');
    }
    
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
         $tags = Tag::all();
        
        return view('tags.index')->with('tags', $tags);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //validate data
        $this->validate($request, array('name' => 'required|max:255'));
        //store in the database
        $tag = new Tag;
        $tag->name = $request->name;
        $tag->save();

        Session::flash('sucess', 'New tag was sucessfully created!');
        return redirect()->route('tag.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/clips/create.blade.php
@extends('layouts.app')
@section('title')
    Create
@stop
@section('stylesheets')
    {!! Html::style('css/select2.min.css') !!}
@endsection

@section('content')

<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Add a New Clip</div>
                <div class="panel-body">
                     {!! Form::open(['route' => 'clip.store', 'class' => 'form-horizontal']) !!}

                        <div class="form-group">
                             {!! Form::label('name', 'Name', ['class' => 'col-md-4 control-label']) !!}

                            <div class="col-md-6">
                                 {!! Form::text('name', null, ['class' => 'form-control','placeholder' => "Enter name"]) !!}

                            </div>
                        </div>

                        <div class="form-group">
                            
                            {!! Form::label('start_time', 'Start Time', ['class' => 'col-md-4 control-label']) !!}
                            <div class="col-md-6">
                                 {!! Form::text('start_time', null, ['class' => 'form-control', 'placeholder' => "Enter a start time"]) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('end_time', 'End Time', ['class' => 'col-md-4 control-label']) !!}

                            <div class="col-md-6">
                                {!! Form::text('end_time', null, ['class' => 'form-control', 'placeholder' => "Enter a end time"]) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('tags', 'Tags', ['class' => 'col-md-4 control-label']) !!}

                            <div class="col-md-6">
                               <select class="form-control select2-multi" name="tags[]" multiple="multiple">
                                  @foreach($tags as $tag)
                                  <option value='{{ $tag->id}}'> {{ $tag->name}} </option>
                                  @endforeach
                               </select>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                {!! Form::submit('Add a Clip', ['class' => 'btn btn-primary']) !!}
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('scripts')
    {!! Html::script('js/select2.min.js') !!}

    <script type="text/javascript">
        $(".select2-multi").select2();
    </script>
@endsection

resources/views/clips/edit.blade.php
@extends('layouts.app')
@section('title')
    Edit {{{$clip->name}}}
@stop

@section('stylesheets')
    {!! Html::style('css/select2.min.css') !!}
@endsection

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Edit Clip</div>
                <div class="panel-body">
                	{!!Form::model($clip, [
						'method' => 'patch', 
						'route' => ['clip.update', $clip->id],
						'class' => 'form-horizontal'
					])!!}

                        <div class="form-group">
                             {!! Form::label('name', 'Name', ['class' => 'col-md-4 control-label']) !!}

                            <div class="col-md-6">
                                 
                                 {!! Form::text('name', $clip->name, ['class' => 'form-control','placeholder' => "Enter name"]) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            
                            {!! Form::label('start_time', 'Start Time', ['class' => 'col-md-4 control-label']) !!}
                            <div class="col-md-6">
                                 {!! Form::text('start_time', $clip->start_time, ['class' => 'form-control', 'placeholder' => "Enter a start time"]) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('end_time', 'End Time', ['class' => 'col-md-4 control-label']) !!}

                            <div class="col-md-6">
                                {!! Form::text('end_time', $clip->end_time, ['class' => 'form-control', 'placeholder' => "Enter a end time"]) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('tags', 'Tags', ['class' => 'col-md-4 control-label']) !!}

                            <div class="col-md-6">
                                 {!! Form::select('tags[]', $tags, null, ['class' => 'form-control select2-multi', 'multiple' => 'multiple']) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                {!! Form::submit('Edit', ['class' => 'btn btn-primary"']) !!}
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

@section('scripts')
    {!! Html::script('js/select2.min.js') !!}

    <script type="text/javascript">
        $(".select2-multi").select2();
        $(".select2-multi").select2().val({!! json_encode($clip->tags()->getRelatedIds()) !!}).trigger("change");
    </script>
@endsection

resources/views/clips/index.blade.php
@extends('layouts.app')
@section('title')
    Video Player Clips
@stop

@section('content')
     <div class="container">
            <h1>Video Player</h1>

            <!-- Begin Media Fragments Example -->
            <div>
              <video id="frag1" controls preload="metadata" width="100%">
                <source src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4"  type='video/mp4;codecs="avc1.42E01E, mp4a.40.2"' data-original="http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4">
                <source src="http://clips.vorwaerts-gmbh.de/big_buck_bunny.webm" type='video/webm;codecs="vp8, vorbis"' data-original="http://clips.vorwaerts-gmbh.de/big_buck_bunny.webm">
              </video>
              <nav>
                @foreach($clips as $clip)
                  <button class="btn btn-primary" data-start="{{$clip->start_time}}" data-end="{{$clip->end_time}}">Play {{$clip->name}}</button>
                @endforeach
              </nav>
            </div>
            <h2>Clip List</h2>
            <div>
              <label>Filter</label>
              <br/>
              <input id="filter" placeholder="Type To Filter" class="form-control">
            </div>

            <div class="row">
              <div class="col-sm-12">
                    <table class="table">
                      <thead>
                        <tr>
                          <th>Name</th>
                          <th>Start Time</th>
                          <th>End Time</th>
                          <th></th>
                        </tr>
                      <thead>

                      <tbody id="fbody">
                        @foreach($clips as $clip)
                        {!!Form::open([
                              'method' => 'delete', 
                              'route' => ['clip.destroy', $clip->id]
                        ])!!}
                        <tr>
                          <td>{{$clip->name}}</td>
                          <td>{{$clip->start_time}}</td>
                          <td>{{$clip->end_time}}</td>
                          <td>
                            @foreach($clip->tags as $tag)
                              {{ $tag->name.', '}}
                            @endforeach
                          </td>
                          <td><a href="{{route('clip.edit', $clip->id)}}" class="btn btn-primary">Edit</a>
                            {!!Form::submit('Delete', ['class' => 'btn btn-primary'])!!}
                            {!!Form::close()!!}</td>
                        </tr>
                        @endforeach
                      <tbody>
                    </table>
              </div>              
            </div>
     </div>
@endsection

@section('scripts')
    {!! Html::script('js/script.js') !!}

@endsection

resources/views/clips/show.blade.php
@extends('layouts.app')
@section('title')
    {{$clip->name}}
@stop

@section('content')
	<div class="container">
		<div class="content">
			<h2> View Video Clip</h2>
			{!!Form::open([
				'method' => 'delete', 
				'route' => ['clip.destroy', $clip->id]
			])!!}
			<p>Name: {{$clip->name}}</p>
			<p>Start Time: {{$clip->start_time}}</p>
			<p>End Time: {{$clip->end_time}}</p>
			                                                       
			<a href="{{route('clip.edit', $clip->id)}}">Edit</a> 
			{!!Form::submit('Delete')!!}
			{!!Form::close()!!}

		</div>
	</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Video Player</title>

    <!-- Fonts -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css" integrity="sha384-XdYbMnZ/QjLh6iI4ogqCTaIjrFk87ip+ekIjefZch0Y+PvJ8CDYtEs1ipDmPorQ+" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700">

    <!-- Styles -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    {{-- <link href="{{ elixir('css/app.css') }}" rel="stylesheet"> --}}

    @yield('stylesheets')

    <style>
        body {
            font-family: 'Lato';
        }

        .fa-btn {
            margin-right: 6px;
        }
    </style>
</head>
<body id="app-layout">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    My Video Player
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                     <li><a href="{{ action("ClipController@index") }}">Video Player</a></li>
                     <li><a href="{{ action("ClipController@create") }}">Add a Clip</a></li>
                     <li><a href="{{ action("TagController@index") }}">Tags</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{{ url('/logout') }}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('content')

    <!-- JavaScripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.min.js" integrity="sha384-I6F5OKECLVtK/BL+8iSLDEHowSAfUo76ZL9+kGAgTRdiByINKJaqTPH/QVNS1VDb" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
    {{-- <script src="{{ elixir('js/app.js') }}"></script> --}}
    @yield('scripts')

</body>
</html>

resources/views/tags/index.blade.php
@extends('layouts.app')
@section('title')
    Tag
@stop

@section('content')
  <div class="container">
    <div class="row">
        <div class="col-sm-8">
          <h2>Tags</h2>
          <table class="table">
            <thead>
              <tr>
                <th>#</th>
                <th>Name</th>
              </tr>
            <thead>

            <tbody>
              @foreach($tags as $tag)
              <tr>
                <th scope="row">{{$tag->id}}</th>
                <td>{{$tag->name}}</td>
              </tr>
              @endforeach
            <tbody>
          </table>
        </div>
        
        <div class="col-sm-4">
          <div class="panel panel-default">
                <div class="panel-heading">Add a New Tag</div>
                <div class="panel-body">
                     {!! Form::open(['route' => 'tag.store', 'class' => 'form-horizontal']) !!}
                             {!! Form::label('name', 'Name', ['class' => 'col-md-4 control-label']) !!}
                             {!! Form::text('name', null, ['class' => 'form-control','placeholder' => "Enter name"]) !!}
                             <br/>
                             {!! Form::submit('Add new tag', ['class' => 'btn btn-primary']) !!}                    
                      
                    {!! Form::close() !!}
                </div>
          </div>
        </div>
    </div>
  </div>
@endsection